export enum RelayItem {
    IronIngot = "G_所持_IID_てつの晶石",
    SteelIngot = "G_所持_IID_はがねの晶石",
    SilverIngot = "G_所持_IID_ぎんの晶石",
    MtCrystal = "G_所持_IID_素材_威力",
    CrtCrystal = "G_所持_IID_素材_必殺",
    DexCrystal = "G_所持_IID_素材_技",
    SpdCrystal = "G_所持_IID_素材_速さ",
    DefCrystal = "G_所持_IID_素材_守備",
    ResCrystal = "G_所持_IID_素材_魔防",
    HitCrystal = "G_所持_IID_素材_命中",
    AvoCrystal = "G_所持_IID_素材_回避",
    CritAvoidCrystal = "G_所持_IID_素材_必避",
    DragonBane = "G_所持_IID_素材_竜特効",
    RiderBane = "G_所持_IID_素材_騎馬特効",
    ArmorBane = "G_所持_IID_素材_重装特効",
    FlierBane = "G_所持_IID_素材_飛行特効",
    CorruptedBane = "G_所持_IID_素材_異形特効",
}